"""Compliance and status reports, and DR runbooks.

- compliance_report(): a self-contained HTML report auditors ask for —
  backup coverage, success rates, changes in the period (expected vs.
  unexpected), unannotated changes, policy findings, and rehearsal
  status. Produced by `otitbup report`, and on a schedule from the daemon
  (reports.schedule / reports.email).
- dr_runbook(): a per-site disaster-recovery runbook — every device's
  latest backup, hashes, and restore instructions — the document that
  goes in the cabinet (`otitbup dr-plan`).

Both are dependency-free HTML (works offline, prints cleanly).
"""
from __future__ import annotations

import html
import time
from datetime import datetime, timezone

from .gitstore import GitStore
from .models import AppConfig
from .policy import check_all, severity_rank
from .restore import DRIVER_INSTRUCTIONS
from .runstore import RunStore

_STYLE = """
body { font-family: system-ui, sans-serif; margin: 2rem; color: #1a1f24; }
h1 { font-size: 1.5rem; } h2 { font-size: 1.15rem; margin-top: 1.8rem; }
table { border-collapse: collapse; width: 100%; margin: .5rem 0; }
th, td { border: 1px solid #ccd; padding: .35rem .6rem; text-align: left;
         font-size: .88rem; }
th { background: #f0f3f6; }
.tiles { display: flex; gap: 1rem; flex-wrap: wrap; margin: 1rem 0; }
.tile { border: 1px solid #ccd; border-radius: 8px; padding: .6rem 1rem; }
.tile b { display: block; font-size: 1.6rem; }
.ok { color: #1b7a2f; } .warn { color: #b26a00; } .bad { color: #b3261e; }
.sev-critical, .sev-high { color: #b3261e; font-weight: 600; }
.sev-medium { color: #b26a00; } .sev-low { color: #5b6570; }
footer { margin-top: 2rem; color: #5b6570; font-size: .8rem; }
"""


def _fmt_age(ts: float | None, now: float) -> str:
    if ts is None:
        return "never"
    days = (now - ts) / 86400
    if days < 1:
        return f"{(now - ts) / 3600:.0f}h ago"
    return f"{days:.0f}d ago"


def _doc(title: str, body: str) -> str:
    return (
        f"<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{html.escape(title)}</title><style>{_STYLE}</style></head>"
        f"<body>{body}<footer>Generated by otitbup</footer></body></html>"
    )


def compliance_report(
    config: AppConfig,
    store: GitStore,
    runstore: RunStore,
    period_days: int = 30,
    now: float | None = None,
) -> str:
    now = now if now is not None else time.time()
    generated = datetime.fromtimestamp(now, timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC"
    )
    period_start = now - period_days * 86400
    devices = config.all_devices()
    annotated = store.annotated_commits()

    covered = never = stale = 0
    unexpected_changes = unannotated = 0
    rows = []
    for device in devices:
        status = runstore.status(device.qualified_name)
        if status.last_success is None:
            never += 1
            coverage = "<span class='bad'>never</span>"
        else:
            covered += 1
            if now - status.last_success > 7 * 86400:
                stale += 1
                coverage = f"<span class='warn'>{_fmt_age(status.last_success, now)}</span>"
            else:
                coverage = f"<span class='ok'>{_fmt_age(status.last_success, now)}</span>"

        period_unexpected = 0
        for run in runstore.recent_runs(device.qualified_name, limit=500):
            if run["started_at"] < period_start or not run["changed"]:
                continue
            if run["expected"] == 0:
                period_unexpected += 1
            if run["commit_hash"] and run["commit_hash"] not in annotated:
                unannotated += 1
        unexpected_changes += period_unexpected

        rehearsal = runstore.last_rehearsal(device.qualified_name)
        rehearsal_cell = (
            _fmt_age(rehearsal["at"], now) if rehearsal
            else "<span class='warn'>never</span>"
        )
        rows.append(
            f"<tr><td>{html.escape(device.qualified_name)}</td>"
            f"<td>{html.escape(device.driver)}</td>"
            f"<td>{coverage}</td>"
            f"<td>{status.consecutive_failures or ''}</td>"
            f"<td>{period_unexpected or ''}</td>"
            f"<td>{rehearsal_cell}</td></tr>"
        )

    policy_findings = check_all(config, store)
    total_findings = sum(len(f) for f in policy_findings.values())
    policy_rows = []
    for device_name in policy_findings:
        for finding in sorted(
            policy_findings[device_name],
            key=lambda f: severity_rank(f.severity), reverse=True,
        ):
            policy_rows.append(
                f"<tr><td>{html.escape(finding.device)}</td>"
                f"<td class='sev-{html.escape(finding.severity)}'>"
                f"{html.escape(finding.severity)}</td>"
                f"<td>{html.escape(finding.rule_id)}</td>"
                f"<td>{html.escape(finding.description)}</td></tr>"
            )

    body = (
        f"<h1>OTITbup compliance report</h1>"
        f"<p>Generated {generated} · period: last {period_days} days · "
        f"{len(devices)} device(s)</p>"
        "<div class='tiles'>"
        f"<div class='tile'><b class='{'ok' if not never else 'bad'}'>"
        f"{covered}/{len(devices)}</b>covered</div>"
        f"<div class='tile'><b class='{'warn' if stale else 'ok'}'>{stale}</b>"
        "stale (&gt;7d)</div>"
        f"<div class='tile'><b class='{'bad' if never else 'ok'}'>{never}</b>"
        "never backed up</div>"
        f"<div class='tile'><b class='{'warn' if unexpected_changes else 'ok'}'>"
        f"{unexpected_changes}</b>unexpected changes</div>"
        f"<div class='tile'><b class='{'warn' if unannotated else 'ok'}'>"
        f"{unannotated}</b>unannotated changes</div>"
        f"<div class='tile'><b class='{'warn' if total_findings else 'ok'}'>"
        f"{total_findings}</b>policy findings</div>"
        "</div>"
        "<h2>Devices</h2>"
        "<table><tr><th>Device</th><th>Driver</th><th>Last backup</th>"
        "<th>Consec. failures</th><th>Unexpected changes</th>"
        "<th>Last rehearsal</th></tr>"
        + "".join(rows) + "</table>"
        "<h2>Policy findings</h2>"
        + (
            "<table><tr><th>Device</th><th>Severity</th><th>Rule</th>"
            "<th>Description</th></tr>" + "".join(policy_rows) + "</table>"
            if policy_rows else "<p class='ok'>No policy findings.</p>"
        )
    )
    return _doc("otitbup compliance report", body)


def dr_runbook(
    config: AppConfig,
    store: GitStore,
    runstore: RunStore,
    site: str,
    now: float | None = None,
) -> str:
    now = now if now is not None else time.time()
    generated = datetime.fromtimestamp(now, timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC"
    )
    site_obj = next((s for s in config.sites if s.name == site), None)
    if site_obj is None:
        raise KeyError(f"unknown site: {site}")

    sections = []
    device_count = 0
    for zone in site_obj.zones:
        for device in zone.devices:
            device_count += 1
            commit = store.last_commit_hash(device)
            if commit:
                manifest = _manifest(store, device, commit)
                artifact_rows = "".join(
                    f"<tr><td>{html.escape(name)}</td>"
                    f"<td>{html.escape(str(meta.get('kind', '')))}</td>"
                    f"<td><code>{html.escape(str(meta.get('sha256', ''))[:16])}"
                    "…</code></td></tr>"
                    for name, meta in sorted(manifest.items())
                )
                backup_line = (
                    f"latest backup <code>{commit[:10]}</code> "
                    f"({html.escape(store.last_commit_info(device))})"
                )
            else:
                artifact_rows = ""
                backup_line = "<span class='bad'>NO BACKUP ON RECORD</span>"
            instructions = DRIVER_INSTRUCTIONS.get(
                device.driver,
                "Restore with the vendor tool appropriate for this device.",
            )
            rehearsal = runstore.last_rehearsal(device.qualified_name)
            rehearsal_line = (
                f"last restore rehearsal: {_fmt_age(rehearsal['at'], now)} "
                f"({html.escape(rehearsal.get('result', ''))})"
                if rehearsal else
                "<span class='warn'>restore never rehearsed</span>"
            )
            sections.append(
                f"<h2>{html.escape(device.qualified_name)}</h2>"
                f"<p>driver <code>{html.escape(device.driver)}</code> · "
                f"address {html.escape(device.address or 'n/a')} · "
                f"{backup_line}</p>"
                f"<p>{rehearsal_line}</p>"
                f"<p><b>Restore procedure:</b> {html.escape(instructions)}</p>"
                + (
                    "<table><tr><th>Artifact</th><th>Kind</th>"
                    "<th>sha256</th></tr>" + artifact_rows + "</table>"
                    if artifact_rows else ""
                )
            )

    body = (
        f"<h1>Disaster recovery runbook — {html.escape(site)}</h1>"
        f"<p>Generated {generated} · {device_count} device(s)</p>"
        "<p>otitbup performs no device writes for PLCs/RTUs: use the stored "
        "artifacts with the vendor tooling below. Export a hash-verified "
        "bundle per device with <code>otitbup restore &lt;device&gt;</code>."
        " Network devices may be restored with "
        "<code>otitbup net-restore &lt;device&gt;</code>.</p>"
        + "".join(sections)
    )
    return _doc(f"otitbup DR runbook — {site}", body)


def _manifest(store: GitStore, device, commit: str) -> dict:
    import yaml
    try:
        raw = store.read_file_at(commit, f"{device.path}/manifest.yml")
        manifest = yaml.safe_load(raw)
        return manifest if isinstance(manifest, dict) else {}
    except Exception:
        return {}
